pipeline {
    agent any
    
    stages {

        stage('build'){
            
            steps{
                echo 'this is buils stage'
            }
        }

        stage('test'){

            steps{

                echo 'this test stage'
            }

        stage('deliver'){

            steps{

                echo ' this is deploy stage'
            }
        }
        }
    }

}
