pipeline{

    agent any

    stages{

        stage('build'){

            steps{
                echo  "this is a build stage"
            }

        }

        stage('test'){
            steps{
                echo "this is a test stage"
            }
        }

        stage('deploy'){
            steps{
                echo " this is a deploy stage "
            }
        }
    }
}